### PR TITLE
Huge Linting PR

### PR DESCRIPTION
**Pull request by wadetandy**
Best way to look at this is by sampling the individual commits for a general idea of what it's doing.  The methodology here was to start with the `tslint:recommended` tslint ruleset to discover errors, and either turn off or fix each error.  Many of them were auto-fixable so it didn't actually take that much time, but I also broke them down into individual commits for the most part so that we could see the impact of fixing specific errors. Open to discussing all of them.

### CODE REVIEW

**Comment by richmolj** [comment]
* Remove semicolons ✅ 
* Consistent Array types ✅ 
* TypeDef whitespace: I like the consistency but personally prefer no space. I'm fine with accepting the majority opinion, just adds to already-long lines IMO.
* No public ✅ 
* Arrow functions - I'm 50/50, but I guess fine for now ✅ 
* String literal autofix - I think I'm good with this, I just don't want it complaining to me when I do *need* to do this (like iterating)
* Shadowed vars 💯 
 * Guard `for...in` 👎  - I tend to think this one is a little overly pedantic, adding 3 lines of code for a scenario I've rarely run into. I think tests should catch this one, not linting.
* Object literal shorthand ✅ 
* Console statements ✅  - though keep in mind we probably need some generic log utility for non-jsorm stuff. I could see a rack-director type thing that logs helpful page info if some flag is set.
* Recommended rules, sure ✅ 
* Prefer const...I might be able to be talked in to this, but it's another one I find a little overly pedantic and something that could cause issues during refactors, setting up future code, etc.
* Prettier, sure ✅ 

Linting on prebuild...should this instead be part of test suite? I am thinking of the scenario where we merge a PR, then have to deal with linting issues before we can release. As long as we lint as part of the PR I'm good.

**Comment by wadetandy** [comment]
TypeDef whitespace: prettier can only autofix nospace anyway, so I switched to that 
Const: I actually agree here but also didn’t see a problem fixing the ones already in place for discussion purposes. Let’s turn this off.
Console: will definitely need to have a solid importable logger before we turn this on for other projects.
For..in: was definitely 50/50 on this but also have no problems merging the changes already in place. Let’s keep these but turn the rule off.
Build step: yes, we will need to add to Travis config, I just haven’t done it yet. Will add that before merging this.

**Comment by wadetandy** [comment]
@richmolj disabled discussed rules and rebuilt `lib` dirs with changes.

**Comment by richmolj** [comment]
We're in agreement 👍

**Pull request merged**
